version: '2'

services:
  face_recognizer:
    container_name: face_recognizer
    build: .
    environment:
      FACE_PATH: known_faces
      KAFKA_URL: 'kafka:29092'
      KAFKA_TOPIC: 'faces'
    networks: 
      - default
      - server_network

networks:
  server_network:
    external: true
